version: 2
jobs:
  lint:
    docker:
      - image: circleci/node:8.11.4
    steps:
      - checkout
      - run: npm install
      - run: npm run lerna bootstrap
      - run: npm run lint
  test:
    docker:
      - image: circleci/node:8.11.4
    steps:
      - checkout
      - run: npm install
      - run: npm run lerna "bootstrap"
      - run: npm run test
workflows:
  version: 2
  test:
    jobs:
      - lint
      - test
