name: Node.js CI

on:
  pull_request:
  push:
    branches:
      - master
jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12.x]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
    - name: Lerna Cache
      uses: actions/cache@v2
      id: lerna-cache
      with:
        path: |
          node_modules
          */*/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
    - run: npm ci
    - run: npm run lerna -- bootstrap
    - run: npm run build
    - run: npm run lint
    - run: npm run build-docs
    - run: npm run test -- --runInBand
    - name: Codecov
      uses: codecov/codecov-action@v1
      with:
        file: .coverage/*.json
      env:
        CI: true
        RUN_INTEGRATION: true

  integration-tests-hangzhounet:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [12.x]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
    - name: Lerna Cache
      uses: actions/cache@v2
      id: lerna-cache
      with:
        path: |
          node_modules
          */*/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
    - run: npm ci
    - run: npm run lerna -- bootstrap
    - run: npm run build
    - run: cd integration-tests && npm run test:hangzhounet -- --maxWorkers=8
      env:
        CI: true
        TEZOS_RPC_HANGZHOUNET: ${{ secrets.TEZOS_RPC_HANGZHOUNET }}

  integration-tests-ithacanet:
    runs-on: ecad-taquito
    strategy:
      matrix:
        node: [12.x]
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node }}
    - name: Lerna Cache
      uses: actions/cache@v2
      id: lerna-cache
      with:
        path: |
          node_modules
          */*/node_modules
        key: ${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
    - run: npm ci
    - run: npm run lerna -- bootstrap
    - run: npm run build
    - run: cd integration-tests && npm run test:ithacanet -- --maxWorkers=8
      env:
        CI: true
        TEZOS_RPC_ITHACANET: ${{ secrets.TEZOS_RPC_ITHACANET }}
